name: CMake Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Google Test
      run: |
        git clone https://github.com/google/googletest.git ${{github.workspace}}/googletest
        cd ${{github.workspace}}/googletest
        git checkout release-1.12.1

    - name: Create Build Directory
      run: |
        mkdir -p ${{github.workspace}}/build
        rm -rf ${{github.workspace}}/build/*

    - name: Configure CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release

    - name: List Build Directory
      run: ls -lR ${{github.workspace}}/build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: ${{github.workspace}}/build
